# Generated by Django 3.1 on 2020-09-18 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolioName', models.CharField(max_length=40, verbose_name='ポートフォリオ名')),
                ('userName', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('introduction1', models.CharField(max_length=400, verbose_name='自己紹介1')),
                ('introduction2', models.CharField(max_length=400, verbose_name='自己紹介2')),
                ('product1', models.CharField(max_length=400, verbose_name='プロダクト1')),
                ('productUrl1', models.CharField(max_length=400, verbose_name='プロダクトURL1')),
                ('product2', models.CharField(max_length=400, verbose_name='プロダクト1')),
                ('productUrl2', models.CharField(max_length=400, verbose_name='プロダクトURL1')),
                ('product3', models.CharField(max_length=400, verbose_name='プロダクト1')),
                ('productUrl3', models.CharField(max_length=400, verbose_name='プロダクトURL1')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='イメージ1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='イメージ2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='イメージ3')),
                ('extra1', models.CharField(max_length=400, verbose_name='プロダクト1')),
                ('extra2', models.CharField(max_length=400, verbose_name='プロダクト2')),
                ('extra3', models.CharField(max_length=400, verbose_name='プロダクト3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
